# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.abdm_profile_share1_request_intent import AbdmProfileShare1RequestIntent

class TestAbdmProfileShare1RequestIntent(unittest.TestCase):
    """AbdmProfileShare1RequestIntent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbdmProfileShare1RequestIntent:
        """Test AbdmProfileShare1RequestIntent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbdmProfileShare1RequestIntent`
        """
        model = AbdmProfileShare1RequestIntent()
        if include_optional:
            return AbdmProfileShare1RequestIntent(
                hip_id = 'abdm_hip01',
                context = 123,
                purpose = 'profile_share'
            )
        else:
            return AbdmProfileShare1RequestIntent(
                hip_id = 'abdm_hip01',
                context = 123,
                purpose = 'profile_share',
        )
        """

    def testAbdmProfileShare1RequestIntent(self):
        """Test AbdmProfileShare1RequestIntent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
