# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.profile_share3_request import ProfileShare3Request

class TestProfileShare3Request(unittest.TestCase):
    """ProfileShare3Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileShare3Request:
        """Test ProfileShare3Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileShare3Request`
        """
        model = ProfileShare3Request()
        if include_optional:
            return ProfileShare3Request(
                abha_address = 'abc@abdm',
                abha_number = 1.337,
                name = 'abdul kalam',
                gender = 'M - Male',
                year_of_birth = 1931,
                address = 'Ramanathapuram, Tamil Nadu',
                district = 'Ramanathapuram',
                state = 'Tamil Nadu',
                intent = abha.models.profile_share_3_request_intent.profile_share_3_request_intent(
                    context = 123, 
                    link_token = '', ),
                meta_data = abha.models.abdm_profile_share_1_request_meta_data.abdm_profile_share_1_request_metaData(
                    lat = 20.5937, 
                    long = 78.9629, )
            )
        else:
            return ProfileShare3Request(
                abha_address = 'abc@abdm',
                intent = abha.models.profile_share_3_request_intent.profile_share_3_request_intent(
                    context = 123, 
                    link_token = '', ),
                meta_data = abha.models.abdm_profile_share_1_request_meta_data.abdm_profile_share_1_request_metaData(
                    lat = 20.5937, 
                    long = 78.9629, ),
        )
        """

    def testProfileShare3Request(self):
        """Test ProfileShare3Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
