# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.api.abdm_link_token_api import AbdmLinkTokenApi


class TestAbdmLinkTokenApi(unittest.TestCase):
    """AbdmLinkTokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AbdmLinkTokenApi()

    def tearDown(self) -> None:
        pass

    def test_abdm_link_token_1(self) -> None:
        """Test case for abdm_link_token_1

        API used to generate link token
        """
        pass


if __name__ == '__main__':
    unittest.main()
