# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.abdm_profile_share1200_response import AbdmProfileShare1200Response

class TestAbdmProfileShare1200Response(unittest.TestCase):
    """AbdmProfileShare1200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbdmProfileShare1200Response:
        """Test AbdmProfileShare1200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbdmProfileShare1200Response`
        """
        model = AbdmProfileShare1200Response()
        if include_optional:
            return AbdmProfileShare1200Response(
                code = 'ABDM-1050',
                message = 'Invalid Profile Share Metadata Keys'
            )
        else:
            return AbdmProfileShare1200Response(
                code = 'ABDM-1050',
                message = 'Invalid Profile Share Metadata Keys',
        )
        """

    def testAbdmProfileShare1200Response(self):
        """Test AbdmProfileShare1200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
