# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.profile_share2_request import ProfileShare2Request

class TestProfileShare2Request(unittest.TestCase):
    """ProfileShare2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileShare2Request:
        """Test ProfileShare2Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileShare2Request`
        """
        model = ProfileShare2Request()
        if include_optional:
            return ProfileShare2Request(
                acknowledgement = abha.models.profile_share_2_request_one_of_acknowledgement.profile_share_2_request_oneOf_acknowledgement(
                    abha_address = 'abc@abdm', 
                    status = 'success', 
                    context = '43', 
                    token_number = '3', 
                    expiry = 180, ),
                response = abha.models.profile_share_2_request_one_of_response.profile_share_2_request_oneOf_response(
                    request_id = '6f0b4665-a915-4c92-aa36-65afb4a2cd71', )
            )
        else:
            return ProfileShare2Request(
                response = abha.models.profile_share_2_request_one_of_response.profile_share_2_request_oneOf_response(
                    request_id = '6f0b4665-a915-4c92-aa36-65afb4a2cd71', ),
        )
        """

    def testProfileShare2Request(self):
        """Test ProfileShare2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
