# coding: utf-8

"""
ABHA Enrollment & Profile Management API V3

It is important to standardize the process of identification of an individual across healthcare providers, to ensure that the created medical records are issued to the right individual or accessed by a Health Information User through appropriate consent. In order to issue an ABHA Number to an individual, one only needs basic demographic details like Name, Year of Birth, Gender. In addition, citizens should be able to update contact information easily. The ABHA Number will be used for the purposes of uniquely identifying persons and authenticating them. An ABHA Address will be used for threading their health records (only with the informed consent of the patient) across multiple systems and stakeholders.   Notes:   1. In case you want to consume the ABHA APIs and use creation on your own interface, use authentication methods as OTP only.   2. In order to have access to ABHA APIs, your clientId must have hid role in gateway. So if you want access to these APIs then please request it in your ABDM on-boarding request.   3. In order to have access to Integrated Programs ABHA APIs, your clientId must have integrated_program role in gateway. So if you want access to these APIs then please request it in your ABDM on-boarding request. Also you will need to share integrated program benefit name to be used in this case.   4. When calling APIs, please ensure that Authorization header must have format as Bearer {Token_Value}. Please note that prefix Bearer is followed by space before the token value.

The version of the OpenAPI document: v3
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from abha.api.abha_enrollment_api import ABHAEnrollmentApi


class TestABHAEnrollmentApi(unittest.TestCase):
    """ABHAEnrollmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ABHAEnrollmentApi()

    def tearDown(self) -> None:
        pass

    def test_api_v3_enrollment_auth_by_aadhaar_post(self) -> None:
        """Test case for api_v3_enrollment_auth_by_aadhaar_post

        AUTH - OF AADHAAR OTP FOR PARENT VERIFICATION
        """
        pass

    def test_api_v3_enrollment_auth_by_abdm_post(self) -> None:
        """Test case for api_v3_enrollment_auth_by_abdm_post

        VERIFY - EMAIL, MOBILE UPDATE
        """
        pass

    def test_api_v3_enrollment_enrol_by_aadhaar_post(self) -> None:
        """Test case for api_v3_enrollment_enrol_by_aadhaar_post

        ENROL - BY AADHAAR VERIFICATION
        """
        pass

    def test_api_v3_enrollment_enrol_by_document_post(self) -> None:
        """Test case for api_v3_enrollment_enrol_by_document_post

        ENROL - BY DOCUMENT
        """
        pass

    def test_api_v3_enrollment_enrol_suggestion_get(self) -> None:
        """Test case for api_v3_enrollment_enrol_suggestion_get

        SUGESSTION
        """
        pass

    def test_api_v3_enrollment_request_otp_post(self) -> None:
        """Test case for api_v3_enrollment_request_otp_post

        REQUEST - OTP FOR ENROLLMENT, UPDATE MOBILE and UPDATE EMAIL
        """
        pass


if __name__ == "__main__":
    unittest.main()
