# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.auth_aadhar_init_request import AuthAadharInitRequest

class TestAuthAadharInitRequest(unittest.TestCase):
    """AuthAadharInitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthAadharInitRequest:
        """Test AuthAadharInitRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthAadharInitRequest`
        """
        model = AuthAadharInitRequest()
        if include_optional:
            return AuthAadharInitRequest(
                auth_method = '',
                txn_id = ''
            )
        else:
            return AuthAadharInitRequest(
                auth_method = '',
                txn_id = '',
        )
        """

    def testAuthAadharInitRequest(self):
        """Test AuthAadharInitRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
