# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.abdm_link_token1_request import AbdmLinkToken1Request

class TestAbdmLinkToken1Request(unittest.TestCase):
    """AbdmLinkToken1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbdmLinkToken1Request:
        """Test AbdmLinkToken1Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbdmLinkToken1Request`
        """
        model = AbdmLinkToken1Request()
        if include_optional:
            return AbdmLinkToken1Request(
                abha_number = 12345678901234,
                abha_address = 'abc@abdm',
                name = 'first_name + middle_name + last_name',
                gender = 'M',
                year_of_birth = 9999
            )
        else:
            return AbdmLinkToken1Request(
                name = 'first_name + middle_name + last_name',
                gender = 'M',
                year_of_birth = 9999,
        )
        """

    def testAbdmLinkToken1Request(self):
        """Test AbdmLinkToken1Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
