# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.abdm_profile_share1_request import AbdmProfileShare1Request

class TestAbdmProfileShare1Request(unittest.TestCase):
    """AbdmProfileShare1Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AbdmProfileShare1Request:
        """Test AbdmProfileShare1Request
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AbdmProfileShare1Request`
        """
        model = AbdmProfileShare1Request()
        if include_optional:
            return AbdmProfileShare1Request(
                intent = abha.models.abdm_profile_share_1_request_intent.abdm_profile_share_1_request_intent(
                    hip_id = 'abdm_hip01', 
                    context = 123, 
                    purpose = 'profile_share', ),
                meta_data = abha.models.abdm_profile_share_1_request_meta_data.abdm_profile_share_1_request_metaData(
                    lat = 20.5937, 
                    long = 78.9629, )
            )
        else:
            return AbdmProfileShare1Request(
                intent = abha.models.abdm_profile_share_1_request_intent.abdm_profile_share_1_request_intent(
                    hip_id = 'abdm_hip01', 
                    context = 123, 
                    purpose = 'profile_share', ),
        )
        """

    def testAbdmProfileShare1Request(self):
        """Test AbdmProfileShare1Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
