# coding: utf-8

"""
    Abdm Abha

    Abdm SDK for abha

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abha.models.link_token1_request_one_of1_error import LinkToken1RequestOneOf1Error

class TestLinkToken1RequestOneOf1Error(unittest.TestCase):
    """LinkToken1RequestOneOf1Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkToken1RequestOneOf1Error:
        """Test LinkToken1RequestOneOf1Error
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkToken1RequestOneOf1Error`
        """
        model = LinkToken1RequestOneOf1Error()
        if include_optional:
            return LinkToken1RequestOneOf1Error(
                code = 'ABDM-1027',
                message = 'You are blocked. Please try again after 24 hours.'
            )
        else:
            return LinkToken1RequestOneOf1Error(
                code = 'ABDM-1027',
                message = 'You are blocked. Please try again after 24 hours.',
        )
        """

    def testLinkToken1RequestOneOf1Error(self):
        """Test LinkToken1RequestOneOf1Error"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
