openapi: 3.0.0
info:
  title: Abdm Abha 
  description: Abdm SDK for abha
  version: 1.0.0
servers:
  - url: https://healthidsbx.abdm.gov.in/api/v1
paths:
  /registration/aadhaar/generateOtp:
    post:
      summary: Generate OTP
      description: This endpoint generates an OTP for Aadhaar number verification.
      operationId: generateOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhaar:
                  type: string
                  description: The Aadhaar number for which to generate the OTP.
                  example: '123452454590'
      responses:
        '200':
          description: OTP generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  txnId:
                    type: string
                    format: uuid
                    example: 'a825f76b-0696-40f3-864c-5a3a5b389a83'
                    description: Based on UUID
        '400':
          description: Bad request (e.g., missing or invalid Aadhaar number)
        '401':
          description: Unauthorized (invalid or missing bearer token)
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

  /registration/aadhaar/verifyOTP:
    post:
      summary: Verify OTP
      description: This endpoint Verfies OTP for Aadhaar number verification.
      operationId: verifyOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
                - txnId
              properties:
                otp:
                  type: string
                  example: 812306
                txnId:
                  type: string
                  example: a825f76b-0696-40f3-864c-5a3a5b389a83
                  description: Based on UUID
      responses:
        '200':
          description: OTP Validated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  txnId:
                    type: string
                    format: uuid
                    example: 'a825f76b-0696-40f3-864c-5a3a5b389a83'
                    description: Based on UUID
        '400':
          description: Bad request (e.g., missing or invalid Aadhaar number)
        '401':
          description: Unauthorized (invalid or missing bearer token)
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
  /registration/aadhaar/generateMobileOTP:
    post:
      summary: Generate Mobile OTP
      description: This endpoint Generates OTP for Abha verification.
      operationId: generateMobileOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mobile
                - txnId
              properties:
                mobile:
                  type: string
                  example: 9545812125
                txnId:
                  type: string
                  example: a825f76b-0696-40f3-864c-5a3a5b389a83
                  description: Based on UUID
      responses:
        '200':
          description: OTP Generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  txnId:
                    type: string
                    format: uuid
                    example: 'a825f76b-0696-40f3-864c-5a3a5b389a83'
                    description: Based on UUID
        '400':
          description: Bad request (e.g., missing or invalid Aadhaar number)
        '401':
          description: Unauthorized (invalid or missing bearer token)
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
  /registration/aadhaar/verifyMobileOTP:
    post:
      summary: Verify Mobile OTP
      description: This endpoint Verfies OTP for Abha verification.
      operationId: verifyMobileOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
                - txnId
              properties:
                otp:
                  type: string
                  example: 812306
                txnId:
                  type: string
                  example: a825f76b-0696-40f3-864c-5a3a5b389a83
                  description: Based on UUID
      responses:
        '200':
          description: OTP Verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  txnId:
                    type: string
                    format: uuid
                    example: 'a825f76b-0696-40f3-864c-5a3a5b389a83'
                    description: Based on UUID
        '400':
          description: Bad request (e.g., missing or invalid Aadhaar number)
        '401':
          description: Unauthorized (invalid or missing bearer token)
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
  /registration/aadhaar/createHealthIdWithPreVerified:
    post:
      summary: Health ID creation
      description: This endpoint Creates Health Id .
      operationId: createHealthIdWithPreVerified
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: Example@Demo.com
                firstName:
                  type: string
                  example: manoj
                healthId:
                  type: string
                  example: deepak.pant
                lastName:
                  type: string
                  example: singh
                middleName:
                  type: string
                  example: kishan
                password:
                  type: string
                  example: India@143
                profilePhoto:
                  type: string
                  example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkJCQkJCQoLCwoODw0PDhQSERESFB4WFxYXFh4uHSEdHSEdLikxKCUoMSlJOTMzOUlUR0NHVGZbW2aBeoGoqOIBCQkJCQkJCgsLCg4PDQ8OFBIRERIUHhYXFhcWHi4dIR0dIR0uKTEoJSgxKUk5MzM5SVRHQ0dUZltbZoF6gaio4v/CABEIBLAHgAMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAACAwABBAUGB//aAAgBAQAAAADwawLpMspcK7qrlE5F0Vtul2bVywMUNeBHUkW/bmxvYELGuNjh2VDvixxo5ViljKjDRMoahCULjs2JCShjhjh2OGxo0Y2MoXHOLszsKLhw7tD99mpZQxj8xceofmLEKFwXLTIyHwY1Ls+iEotjHY0M0pjRYxtGj4VFKLPohQlFQyy4Qipc0XG9pS+CP/2Q==
                  description: Encoded with Base 64
                txnId:
                  type: string
                  example: a825f76b-0696-40f3-864c-5a3a5b389a83
                  description: Based on UUID
      responses:
        '200':
          description: Health Id Created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  authMethods:
                    type: array
                    example: AADHAAR_OTP
                    description: Based on authMethods
                    items:
                      type: string
                      enum:
                        - AADHAAR_OTP
                        - MOBILE_OTP
                        - PASSWORD
                        - DEMOGRAPHICS
                        - AADHAAR_BIO
                  dayOfBirth:
                    type: string
                    example: 23
                  districtCode:
                    type: string
                    example: 401
                  districtName:
                    type: string
                    example: Pune
                  email:
                    type: string
                    example: Example@demo.com
                  firstName:
                    type: string
                    example: akash
                  gender:
                    type: string
                    example: M
                    enum:
                      - M
                      - F
                      - O
                      - U
                  healthId:
                    type: string
                    example: deepak.pant
                  healthIdNumber:
                    type: string
                    example: 43-4221-5105-6749
                  kycPhoto:
                    type: string
                    example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkJCQkJCQoLCwoODw0PDhQSERESFB4WFxYXFh4uHSEdHSEdLikxKCUoMSlJOTMzOUlUR0NHVGZbW2aBeoGoqOIBCQkJCQkJCgsLCg4PDQ8OFBIRERIUHhYXFhcWHi4dIR0dIR0uKTEoJSgxKUk5MzM5SVRHQ0dUZltbZoF6gaio4v/CABEIBLAHgAMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAACAwABBAUGB//aAAgBAQAAAADwawLpMspcK7qrlE5F0Vtul2bVywMUNeBHUkW/bmxvYELGuNjh2VDvixxo5ViljKjDRMoahCULjs2JCShjhjh2OGxo0Y2MoXHOLszsKLhw7tD99mpZQxj8xceofmLEKFwXLTIyHwY1Ls+iEotjHY0M0pjRYxtGj4VFKLPohQlFQyy4Qipc0XG9pS+CP/2Q==
                    description: Encoded with Base 64
                  lastName:
                    type: string
                    example: singh
                  middleName:
                    type: string
                    example: pramod
                  mobile:
                    type: string
                    example: 9545812125
                  monthOfBirth:
                    type: string
                    example: '05'
                  name:
                    type: string
                    example: kishan kumar singh
                  new:
                    type: boolean
                  profilePhoto:
                    type: string
                    example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkJCQkJCQoLCwoODw0PDhQSERESFB4WFxYXFh4uHSEdHSEdLikxKCUoMSlJOTMzOUlUR0NHVGZbW2aBeoGoqOIBCQkJCQkJCgsLCg4PDQ8OFBIRERIUHhYXFhcWHi4dIR0dIR0uKTEoJSgxKUk5MzM5SVRHQ0dUZltbZoF6gaio4v/CABEIBLAHgAMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAACAwABBAUGB//aAAgBAQAAAADwawLpMspcK7qrlE5F0Vtul2bVywMUNeBHUkW/bmxvYELGuNjh2VDvixxo5ViljKjDRMoahCULjs2JCShjhjh2OGxo0Y2MoXHOLszsKLhw7tD99mpZQxj8xceofmLEKFwXLTIyHwY1Ls+iEotjHY0M0pjRYxtGj4VFKLPohQlFQyy4Qipc0XG9pS+CP/2Q==
                    description: Encoded with Base 64
                  refreshToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                    description: JWT Bearer Token
                  stateCode:
                    type: string
                    example: 27
                  stateName:
                    type: string
                    example: MAHARASHTRA
                  tags:
                    type: object
                    additionalProperties:
                      type: string
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                    description: JWT Bearer Token
                  yearOfBirth:
                    type: string
                    example: 1995
        '400':
          description: Bad request (e.g., missing or invalid Aadhaar number)
        '401':
          description: Unauthorized (invalid or missing bearer token)
        '500':
          description: Internal server error
      security:
        - bearerAuth: []


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT