# coding: utf-8

"""
    Gateway

    Gateway is the hub that routes/orchestrates the interaction between consent managers and API bridges. There are 5 categories of APIs; discovery, link, consent flow, data flow and  monitoring. To reflect the consumers of APIs, the above apis are also categorized under cm facing, hiu facing and hip facing 

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm_gateway.api.hip_facing_api import HipFacingApi


class TestHipFacingApi(unittest.TestCase):
    """HipFacingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HipFacingApi()

    def tearDown(self) -> None:
        pass

    def test_v05_consents_hip_on_notify_post(self) -> None:
        """Test case for v05_consents_hip_on_notify_post

        Consent notification
        """
        pass

    def test_v05_health_information_hip_on_request_post(self) -> None:
        """Test case for v05_health_information_hip_on_request_post

        Health information data request
        """
        pass

    def test_v05_health_information_notify_post(self) -> None:
        """Test case for v05_health_information_notify_post

        Notifications corresponding to events during data flow
        """
        pass

    def test_v05_links_context_notify_post(self) -> None:
        """Test case for v05_links_context_notify_post

        This API is meant to be called by HIPs when there is new health data generated for a patient, against a care context that is already linked to patient's ABDM account.
        """
        pass

    def test_v05_links_link_add_contexts_post(self) -> None:
        """Test case for v05_links_link_add_contexts_post

        API for HIP initiated care-context linking for patient
        """
        pass

    def test_v05_links_link_on_confirm_post(self) -> None:
        """Test case for v05_links_link_on_confirm_post

        Token authenticated by HIP, indicating completion of linkage of care-contexts
        """
        pass

    def test_v05_links_link_on_init_post(self) -> None:
        """Test case for v05_links_link_on_init_post

        Response to patient's care context link request
        """
        pass

    def test_v05_patients_sms_notify_post(self) -> None:
        """Test case for v05_patients_sms_notify_post

        API for HIP to send SMS notifications to patients
        """
        pass

    def test_v05_patients_status_on_notify_post(self) -> None:
        """Test case for v05_patients_status_on_notify_post

        Acknowledgment by HIP/HIU
        """
        pass

    def test_v05_users_auth_confirm_post(self) -> None:
        """Test case for v05_users_auth_confirm_post

        Confirmation request sending token, otp or other authentication details from HIP/HIU for confirmation
        """
        pass

    def test_v05_users_auth_fetch_modes_post(self) -> None:
        """Test case for v05_users_auth_fetch_modes_post

        Get a patient's authentication modes relevant to specified purpose
        """
        pass

    def test_v05_users_auth_init_post(self) -> None:
        """Test case for v05_users_auth_init_post

        Initialize authentication from HIP
        """
        pass

    def test_v05_users_auth_on_notify_post(self) -> None:
        """Test case for v05_users_auth_on_notify_post

        callback API by HIU/HIPs as acknowledgement of auth notification
        """
        pass


if __name__ == '__main__':
    unittest.main()
