# coding: utf-8

"""
    Gateway

    Gateway is the hub that routes/orchestrates the interaction between consent managers and API bridges. There are 5 categories of APIs; discovery, link, consent flow, data flow and  monitoring. To reflect the consumers of APIs, the above apis are also categorized under cm facing, hiu facing and hip facing 

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm_gateway.models.hip_data_notification_request import HipDataNotificationRequest

class TestHipDataNotificationRequest(unittest.TestCase):
    """HipDataNotificationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HipDataNotificationRequest:
        """Test HipDataNotificationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HipDataNotificationRequest`
        """
        model = HipDataNotificationRequest()
        if include_optional:
            return HipDataNotificationRequest(
                request_id = '5f7a535d-a3fd-416b-b069-c97d021fbacd',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                notification = abdm_gateway.models.hip_data_notification_request_notification.HipDataNotificationRequest_notification(
                    patient = abdm_gateway.models.hip_data_notification_request_notification_patient.HipDataNotificationRequest_notification_patient(
                        id = 'hinapatel@ncg', ), 
                    care_context = abdm_gateway.models.care_context_definition.CareContextDefinition(
                        patient_reference = 'batman@tmh', 
                        care_context_reference = 'Episode1', ), 
                    hi_types = [
                        'OPConsultation'
                        ], 
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    hip = abdm_gateway.models.hip_data_notification_request_notification_hip.HipDataNotificationRequest_notification_hip(
                        id = '1000010', ), )
            )
        else:
            return HipDataNotificationRequest(
                request_id = '5f7a535d-a3fd-416b-b069-c97d021fbacd',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                notification = abdm_gateway.models.hip_data_notification_request_notification.HipDataNotificationRequest_notification(
                    patient = abdm_gateway.models.hip_data_notification_request_notification_patient.HipDataNotificationRequest_notification_patient(
                        id = 'hinapatel@ncg', ), 
                    care_context = abdm_gateway.models.care_context_definition.CareContextDefinition(
                        patient_reference = 'batman@tmh', 
                        care_context_reference = 'Episode1', ), 
                    hi_types = [
                        'OPConsultation'
                        ], 
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    hip = abdm_gateway.models.hip_data_notification_request_notification_hip.HipDataNotificationRequest_notification_hip(
                        id = '1000010', ), ),
        )
        """

    def testHipDataNotificationRequest(self):
        """Test HipDataNotificationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
