# coding: utf-8

"""
    Gateway

    Gateway is the hub that routes/orchestrates the interaction between consent managers and API bridges. There are 5 categories of APIs; discovery, link, consent flow, data flow and  monitoring. To reflect the consumers of APIs, the above apis are also categorized under cm facing, hiu facing and hip facing 

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm_gateway.models.hip_consent_notification_notification_consent_detail_care_contexts_inner import HIPConsentNotificationNotificationConsentDetailCareContextsInner

class TestHIPConsentNotificationNotificationConsentDetailCareContextsInner(unittest.TestCase):
    """HIPConsentNotificationNotificationConsentDetailCareContextsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HIPConsentNotificationNotificationConsentDetailCareContextsInner:
        """Test HIPConsentNotificationNotificationConsentDetailCareContextsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HIPConsentNotificationNotificationConsentDetailCareContextsInner`
        """
        model = HIPConsentNotificationNotificationConsentDetailCareContextsInner()
        if include_optional:
            return HIPConsentNotificationNotificationConsentDetailCareContextsInner(
                patient_reference = 'hinapatel79@hospital',
                care_context_reference = 'Episode1'
            )
        else:
            return HIPConsentNotificationNotificationConsentDetailCareContextsInner(
                patient_reference = 'hinapatel79@hospital',
                care_context_reference = 'Episode1',
        )
        """

    def testHIPConsentNotificationNotificationConsentDetailCareContextsInner(self):
        """Test HIPConsentNotificationNotificationConsentDetailCareContextsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
