# coding: utf-8

"""
    Gateway

    Gateway is the hub that routes/orchestrates the interaction between consent managers and API bridges. There are 5 categories of APIs; discovery, link, consent flow, data flow and  monitoring. To reflect the consumers of APIs, the above apis are also categorized under cm facing, hiu facing and hip facing 

    The version of the OpenAPI document: 0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from abdm_gateway.models.hiu_subscription_event_content import HIUSubscriptionEventContent

class TestHIUSubscriptionEventContent(unittest.TestCase):
    """HIUSubscriptionEventContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HIUSubscriptionEventContent:
        """Test HIUSubscriptionEventContent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HIUSubscriptionEventContent`
        """
        model = HIUSubscriptionEventContent()
        if include_optional:
            return HIUSubscriptionEventContent(
                patient = abdm_gateway.models.consent_manager_patient_id.ConsentManagerPatientID(
                    id = 'hinapatel79@ndhm', ),
                hip = abdm_gateway.models.organization_representation.OrganizationRepresentation(
                    id = '', ),
                context = [
                    abdm_gateway.models.event_category_detail.EventCategoryDetail(
                        care_context = abdm_gateway.models.care_context_definition.CareContextDefinition(
                            patient_reference = 'batman@tmh', 
                            care_context_reference = 'Episode1', ), 
                        hi_types = [
                            'OPConsultation'
                            ], )
                    ]
            )
        else:
            return HIUSubscriptionEventContent(
                patient = abdm_gateway.models.consent_manager_patient_id.ConsentManagerPatientID(
                    id = 'hinapatel79@ndhm', ),
                hip = abdm_gateway.models.organization_representation.OrganizationRepresentation(
                    id = '', ),
                context = [
                    abdm_gateway.models.event_category_detail.EventCategoryDetail(
                        care_context = abdm_gateway.models.care_context_definition.CareContextDefinition(
                            patient_reference = 'batman@tmh', 
                            care_context_reference = 'Episode1', ), 
                        hi_types = [
                            'OPConsultation'
                            ], )
                    ],
        )
        """

    def testHIUSubscriptionEventContent(self):
        """Test HIUSubscriptionEventContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
